name: Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build XNUVuln
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Theos
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

      - name: Setup Environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Make XNUVuln
        run: make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: XNUVuln.ipa
          path: ./packages/XNUVuln.ipa
  update-release:
    name: Release .ipa
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Delete old release
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        delete_release: true
        tag_name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get artifacts
      uses: actions/download-artifact@v3
      with:
        name: XNUVuln.ipa
    - name: Create new release
      uses: ncipollo/release-action@v1
      with:
        name: Rolling Release
        body: These are automatically updated builds of the latest commit.
        artifacts: "XNUVuln.ipa"
        tag: release
        token: ${{ secrets.GITHUB_TOKEN }}
